local M = {
	hint = "",
	info = "",
	warning = "",
	error = "",
	symlink = "",
	settings = "",
	quit = "",
	indicator = "",
	modified = "●",
	close = "", --  '',
	left_marker = "",
	right_marker = "",
	update = "ﮮ",
	breadcrumb = "»",
	separator = "➜",
	group = "+",

	debug = {
		breakpoint = "",
		stopped = "x",
	},

	find = {
		find_file = "",
		find_project = "",
		find_text = "",
	},
	git = {
		unstaged = "",
		staged = "",
		unmerged = "",
		renamed = "➜",
		untracked = "",
		deleted = "",
		ignored = "◌",
		line_added = "▎",
		line_changed = "▎",
		line_deleted = "契",
		line_topdeleted = "契",
		line_changedelete = "▎",
		nb_line_added = "",
		nb_line_changed = "",
		nb_line_deleted = "",
	},
	file = {
		default = "",
		new_file = "",
		recently_used = "",
		symlink = "",
	},
	folder = {
		arrow_open = "",
		arrow_closed = "",
		default = "",
		open = "",
		empty = "",
		empty_open = "",
		symlink = "",
		symlink_open = "",
	},
	kind_icons = {
		--   פּ ﯟ   some other good icons
		-- find more here: https://www.nerdfonts.com/cheat-sheet
		Text = "",
		Method = "m",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
}

return M
